# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Movie.create!([
  {title: "Aquaman", trailer: "Poop", starring: "Jason Momoa", info: "Arthur Curry learns that he is the heir to the underwater kingdom of Atlantis, and must step forward to lead his people and to be a hero to the world.", genre: "Action", rating: 8},
  {title: "Genesis 2.0", trailer: "Poop", starring: "People", info: "Oscar-nominated Swiss filmmaker Christian Frei's (WAR PHOTOGRAPHER) new documentary observes the harsh and dangerous life of woolly mammoth hunters, native Yakuts on the remote New Siberian Islands in the far north of Siberia. Preserved for millenniums by permafrost, the thawing landscape reveals fossil ivory in a gold rush like atmosphere. When a completely preserved mammoth carcass with fur, liquid blood and muscle tissue is discovered, a new, high-stakes scientific and potentially lucrative quest to resurrect the species à la Jurassic Park mounts. Worldwide, biologists from the Chinese National GeneBank to Harvard's Medical School are working on reinventing life to make virus-resistant human cells, reanimate extinct species, and build an entire human genome from scratch. GENESIS 2.0 approaches this burgeoning revolution in science with both curiosity and skepticism.", genre: "Documentary", rating: 84},
  {title: "Mary Poppins", trailer: "Poop", starring: "Emily Blunt", info: "Directed and produced by Rob Marshall, Mary Poppins Returns also stars Lin-Manuel Miranda, Ben Whishaw, Emily Mortimer and Julie Walters with Colin Firth and Meryl Streep. The film, which introduces three new Banks children, played by Pixie Davies, Nathanael Saleh and newcomer Joel Dawson, also features Dick Van Dyke and Angela Lansbury. The film is set in 1930s depression-era London (the time period of the original novels) and is drawn from the wealth of material in PL Travers' additional seven books. In the story, Michael (Whishaw) and Jane (Mortimer) are now grown up, with Michael, his three children and their housekeeper, Ellen (Walters), living on Cherry Tree Lane. After Michael suffers a personal loss, the enigmatic nanny Mary Poppins (Blunt) re-enters the lives of the Banks family, and, along with the optimistic street lamplighter Jack (Miranda), uses her unique magical skills to help the family rediscover the joy and wonder missing in their lives. Mary Poppins also introduces the children to a new assortment of colorful and whimsical characters, including her eccentric cousin, Topsy (Streep). The film is produced by Marshall, John DeLuca and Marc Platt. The screenplay is by David Magee based on The Mary Poppins Stories by PL Travers with Marc Shaiman and Scott Wittman writing all new songs and Shaiman composing an original score.", genre: "Fantasy", rating: 78},
  {title: "Wreck it Ralph", trailer: "Poop", starring: "John C. Reilly, Gal Gadot", info: "In Ralph Breaks the Internet, video-game bad guy Ralph (voice of John C. Reilly) and best friend Vanellope von Schweetz (voice of Sarah Silverman) leave the comforts of Litwak's arcade in an attempt to save her game, Sugar Rush. Their quest takes them to the vast, uncharted world of the internet where they rely on the citizens of the internet--the Netizens--to help navigate their way. Lending a virtual hand are Yesss (voice of Taraji P. Henson), the head algorithm and the heart and soul of the trend-making site BuzzzTube, and Shank (voice of Gal Gadot), a tough-as-nails driver from a gritty online auto-racing game called Slaughter Race, a place Vanellope wholeheartedly embraces--so much so that Ralph worries he may lose the only friend he's ever had.", genre: "Fantasy", rating: 78},
  {title: "Bumblebee", trailer: "Poop", starring: "Hailee Steinfeld, John Cena", info: "On the run in the year 1987, Bumblebee finds refuge in a junkyard in a small Californian beach town. Charlie (Hailee Steinfeld), on the cusp of turning 18 and trying to find her place in the world, discovers Bumblebee, battle-scarred and broken. When Charlie revives him, she quickly learns this is no ordinary, yellow VW bug.", genre: "Action", rating: 92},
  {title: "Holmes and Watson", trailer: "Poop", starring: "Will Ferrell, John C. Reilly", info: "Legendary detective Sherlock Holmes and his partner Doctor Watson return for a comedic take on their classic literary partnership, as they use their incredible deductive minds to solve a mystery.",genre: "Comedy",rating: 9},
  {title: "Spiderman into the Spiderverse", trailer: "Poop", starring: "Shameik Moore, Jake Johnson", info: "Phil Lord and Christopher Miller, the creative minds behind The Lego Movie and 21 Jump Street, bring their unique talents to a fresh vision of a different Spider-Man Universe, with a groundbreaking visual style that's the first of its kind. Spider-Man: Into the Spider-Verse introduces Brooklyn teen Miles Morales, and the limitless possibilities of the Spider-Verse, where more than one can wear the mask.",genre: "Action, Animated",rating: 97},
  {title: "Vice", trailer: "poop", starring: "Christian Bale, Same Rockwell", info: 'VICE explores the epic story about how a bureaucratic Washington insider quietly became the most powerful man in the world as Vice-President to George W. Bush, reshaping the country and the globe in ways that we still feel today.', genre: "Drama", rating: 64},
  {title: "The Grinch", trailer: "poop", starring: "Benedict Cumberbatch, Rashida Jones", info: "Each year at Christmas they disrupt his tranquil solitude with their increasingly bigger, brighter and louder celebrations. When the Whos declare they are going to make Christmas three times bigger this year, the Grinch realizes there is only one way for him to gain some peace and quiet: he must steal Christmas. To do so, he decides he will pose as Santa Claus on Christmas Eve, even going so far as to trap a lackadaisical misfit reindeer to pull his sleigh. Meanwhile, down in Who-ville, Cindy-Lou Who-a young girl overflowing with holiday cheer-plots with her gang of friends to trap Santa Claus as he makes his Christmas Eve rounds so that she can thank him for help for her overworked single mother. As Christmas approaches, however, her good-natured scheme threatens to collide with the Grinch's more nefarious one. Will Cindy-Lou achieve her goal of finally meeting Santa Claus? Will the Grinch succeed in silencing the Whos' holiday cheer once and for all?", genre: "Animated",rating: 58},
  # {title: "The Upside", trailer: "poop", starring: "Bryan Cranston, Kevin Hart", info: "Inspired by a true story, The Upside is a heartfelt comedy about a recently paroled ex-convict (Kevin Hart) who strikes up an unusual and unlikely friendship with a paralyzed billionaire (Bryan Cranston). Directed by Neil Burger and written by Jon Hartmere, The Upside is based on the hit 2011 French film The Intouchables.", genre: "Drama", rating: 55},
  {title: "Touch Me Not", trailer: "poop", starring: "Laura Benson, Tómas Lemarquis ", info: "On the fluid border between reality and fiction, TOUCH ME NOT follows the emotional journeys of Laura, Tómas and Christian, offering a deeply empathic insight into their lives. Craving for intimacy yet also deeply afraid of it, they work to overcome old patterns, defense mechanisms and taboos, to cut the cord and finally be free.", genre: "Drama", rating: 55},
  {title: "Escape Room", trailer: 'poop', starring: "Taylor Russell, Logan Miller", info: 'Escape Room is a psychological thriller about six strangers who find themselves in circumstances beyond their control and must use their wits to find the clues or die.', genre: "Horror", rating: 91},
  {title: "The Vanishing", trailer: 'poop', starring: "Gerard Butler, Peter Mullen", info: "Gerard Butler (Hunter Killer) and Peter Mullan (Ozark) star in this tense, action-packed thriller based on true events. After three lighthouse keepers arrive for work on a remote Scottish isle, they make a fateful discovery: a wrecked rowboat-with a chest full of gold. As a mysterious boat heads toward the island, the three men make a choice that will change their lives forever,
  ensnaring them in a web of greed, paranoia, and murder.", genre: "Mystery & Suspense", rating: 91},
  {title: "State Like Sleep", trailer: 'poop', starring: "Kathering Waterson, Michael Shannon", info: "One year after her husband's (Michiel Huisman) untimely death, a young widow (Katherine Waterston) receives an unsettling phone call that forces her to revisit the past.", genre: "Mystery & Suspense", rating: 63},
  {title: "Rust Creek", trailer: 'poop', starring: "Hermione Corfield, Jay Paulson", info: "An ordinary woman must summon extraordinary courage to survive a nightmare odyssey in this harrowing survival thriller. Sawyer (Hermione Corfield) is an ambitious, overachieving college senior with a seemingly bright future. While on her way to a job interview, a wrong turn leaves her stranded deep in the frozen Kentucky woods. Suddenly, the young woman with everything to live for finds herself facing her own mortality as she's punished by the elements and pursued by a band of ruthless outlaws. With nowhere left to run, she is forced into an uneasy alliance with Lowell (Jay Paulson), an enigmatic loner with shadowy intentions. Though she's not sure she can trust him, Sawyer must take a chance if she hopes to escape Rust Creek alive.", genre: "Drama, Mystery & Suspense", rating: 82},
  {title: "The Upside", trailer: 'poop', starring: "Bryan Cranston, Kevin Hart", info: 'Inspired by a true story, The Upside is a heartfelt comedy about a recently paroled ex-convict (Kevin Hart) who strikes up an unusual and unlikely friendship with a paralyzed billionaire (Bryan Cranston). Directed by Neil Burger and written by Jon Hartmere, The Upside is based on the hit 2011 French film The Intouchables.', genre: "Drama", rating: 55},
  {title: "Replicas", trailer: 'poop', starring: "Keanu Reeves, Alice Eve", info: 'After a car accident kills his family, a daring synthetic biologist (Reeves) will stop at nothing to bring them back, even if it means pitting himself against a government-controlled laboratory, a police task force, and the physical laws of science.', genre: "Mystery & Suspense", rating: 94},
  {title: "Buffalo Boys", trailer: 'poop', starring: "Yoshi Sudarso, Ario Bayu", info: "In 19th Century Java, a brutal massacre and the murder of Sultan Hamza by Captain Van Trach and his Dutch soldiers force Arana, Jamar and Suwo -- the sultan's brother and infant sons -- to flee the country, bringing them halfway around the world to the American Wild West. After working the railroads and learning the cowboy way of life, Arana tells the boys it's time to return to their homeland and avenge their father's death. Back on Indonesian soil, the hunt for their father's killer begins. Along the way, they meet some villagers including Kiona, the rebellious and beautiful headman's daughter who Suwo falls for, and soon find out that the treacherous Van Trach still rules the area. Their presence puts the village in danger, quickly turning their quest for revenge into a fight for freedom. With the odds stacked against them, Arana, Jamar and Suwo use the skills they learned from the wilds of America to face Van Trach and his army in a showdown for justice.", genre: "Action", rating: 80},
  {title: "Glass", trailer: 'poop', starring: "Bruce Willis, Samuel L Jackson, James McAvoy", info: "From Unbreakable, Bruce Willis returns as David Dunn as does Samuel L. Jackson as Elijah Price, known also by his pseudonym Mr. Glass. Joining from Split are James McAvoy, reprising his role as Kevin Wendell Crumb and the multiple identities who reside within, and Anya Taylor-Joy as Casey Cooke, the only captive to survive an encounter with The Beast. Following the conclusion of Split, Glass finds Dunn pursuing Crumb's superhuman figure of The Beast in a series of escalating encounters, while the shadowy presence of Price emerges as an orchestrator who holds secrets critical to both men.", genre: "Horror", rating: 99},
  {title: "Serenity", trailer: 'poop', starring: "Matthew McConaughey, Anne Hathaway, Jason Clarke", info: 'From the creative mind of Oscar nominee Steven Knight comes a daringly original, sexy, stylized thriller. Baker Dill (Academy Award winner Matthew McConaughey) is a fishing boat captain leading tours off a tranquil, tropical enclave called Plymouth Island. His quiet life is shattered, however, when his ex-wife Karen (Academy Award winner Anne Hathaway) tracks him down with a desperate plea for help. She begs Dill to save her - and their young son - from her new, violent husband (Jason Clarke) by taking him out to sea on a fishing excursion, only to throw him to the sharks and leave him for dead. Karens appearance thrusts Dill back into a life hed tried to forget, and as he struggles between right and wrong, his world is plunged into a new reality that may not be all that it seems.', genre: "Mystery & Suspense", rating: 94}
])

User.create!([
  {username: "Poopy Pants Mcgee"},
  {username: "The Hulkster"},
  {username: "Steve Rogers"},
  {username: "Bruce Wayne"},
  {username: "Homer Simpson"},
  {username: "Peter Griffin"},
  {username: "James Brown"},
  {username: "Tony Stark"},
  {username: "TheStrongestAvenger_Thor"},
  {username: "ThanosIsTheWinner23"},
  {username: "RubyIsBetterThanJavascript40"},
  {username: "IvanDrago1"},
  {username: "RockyBalboa"},
  {username: "MrT90"},
  {username: "ATeam00"},
  {username: "JasonCr50"},
  {username: "AdamG99"},
  {username: "GMoor23"},
  {username: "CoffeeDad"},
  {username: "MmmmBeer5"},
  {username: "Dude"},
])


Comment.create!([
  {movie_id: 84, user_id: 1, comment: "This movie is unbelievable!"},
  {movie_id: 85, user_id: 2, comment: "On a scale of 1 to 10, it was a 0"},
  {movie_id: 86, user_id: 3, comment: "Beyond Horrendous."},
  {movie_id: 120, user_id: 4, comment: "The first word that comes to mind...crap."},
  {movie_id: 121, user_id: 5, comment: "If Heaven exist, this movie plays on a loop there."},
  {movie_id: 122, user_id: 6, comment: "OMG, wtf!"},
  {movie_id: 124, user_id: 7, comment: "I brought a friend with me, even he didnt like it.  It was my dog."},
  {movie_id: 123, user_id: 8, comment: "Pure unadulterated awesomness."},
  {movie_id: 125, user_id: 9, comment: "Im in love with this movie...I might marry it."},
  {movie_id: 126, user_id: 10, comment: "Wow, just wow...and not in a good way."},
  {movie_id: 129, user_id: 11, comment: "I cant even."}
])
